### ISSUE TITLE
Server unavailable causes crash

### ISSUE THREAD

**Issue by danil179** [MatthewFrench/LeagueSandboxAutoSetup#5]
https://github.com/LeagueSandbox/LeagueSandboxAutoSetup/blob/da80da76c8ddb869862b6501df498bd3889e4072/League%20Sandbox%20Auto%20Setup/Form1.cs#L146

As the url is no longer working, it needs to be changed to a new URL.
Also, add error messages for such cases.

**Comment by samuelGrahame** [comment]
Not sure if you want to use my fork: 
https://github.com/samuelGrahame/LeagueSandboxAutoSetup

i have changed it to open the link from google drive, you just save the .7z file in the same directory you choose. it will also set all projects to prefer / x86. it will also set correct path to GameServerSettings for the exact path of league of legends.exe

i also added so it will clone each sub repository manually for some reason it failed... when running from code.
